#!groovy
buildViaJervis()
pipeline {
    agent {
        label 'ubuntu1604'
    }
    stages {
        stage('Simulated deploy') {
            when {
                expression {
                    ! env.IS_PULL_REQUEST
                }
            }
            steps {
                unstash 'artifacts'
                unstash 'cobertura'
                unstash 'junit'
                sh 'find . -type f'
            }
        }
    }
}
