name: Unit Tests

# Trigger
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - build.gradle
      - gradle.properties
      - resources/**
      - src/**
      - vars/**
  pull_request:
    types: [opened, synchronize]
    paths:
      - .github/workflows/**
      - build.gradle
      - gradle.properties
      - resources/**
      - src/**
      - vars/**

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java: [ '17', '21' ]
        groovy:
          - ${{ vars.GROOVY_2_4 }}
          - ${{ vars.GROOVY_2_5 }}
          - ${{ vars.GROOVY_3_0 }}
          - ${{ vars.GROOVY_4_0 }}
        #exclude:
        #  - groovy: ${{ vars.GROOVY_2_4 }}
        #    java: '21'
        #  - groovy: ${{ vars.GROOVY_2_5 }}
        #    java: '21'
    name: Java ${{ matrix.java }} Groovy ${{ matrix.groovy }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      #- if: ${{ !(matrix.groovy == vars.GROOVY_4_0 && matrix.java == '17') }}
      - name: Unit Tests
        run: GROOVY_VERSION=${{ matrix.groovy }} ./gradlew check
      #- if: ${{ matrix.groovy == vars.GROOVY_4_0 && matrix.java == '17' }}
      - name: Coveralls Test Coverage
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: GROOVY_VERSION=${{ matrix.groovy }} ./gradlew coveralls
